services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    command: >
      /bin/sh -c "wget -q -O /usr/share/nginx/html/index.html
      https://raw.githubusercontent.com/juniorsousa-oss/NEXON-TESTE/main/index.html
      && wget -q -O /usr/share/nginx/html/logo.svg
      https://raw.githubusercontent.com/juniorsousa-oss/NEXON-TESTE/main/logo.svg
      && exec nginx -g 'daemon off;'"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.nexon-teste.rule=Host(`teste.nexonlabs.com.br`)"
      - traefik.http.routers.nexon-teste.entrypoints=websecure
      - traefik.http.routers.nexon-teste.tls=true
      - traefik.http.routers.nexon-teste.tls.certresolver=letsencrypt
      - traefik.http.services.nexon-teste.loadbalancer.server.port=80
